# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrw-ftMDkX04n-wuA5bK8MdipG3F8BWe
"""

import random #[] 🟩🟨⬜
words = ["arbol", "datos", "lista", "avion", "bueno", "playa", "cebra", "zorro"] #You can add your own words here/Puedes añadir tus propias palabras aquí.
random_words = random.choice(words)
for x in range(0, 6):
  guess = list(input("¿Cuál es la palabra?")) #"What's the word?"
  if len(guess) < 5 or len(guess) > 5:
    print("La palabra debe tener 5 letras.") #"The word must be a 5-character word."
  else:
    if guess[0] in random_words[0]:
      print(guess[0], ":🟩")
    elif guess[0] not in random_words:
      print(guess[0], ":⬜")
    elif guess[0] in random_words[1] or guess[0] in random_words[2] or guess[0] in random_words[3] or guess[0] in random_words[4]:
      print(guess[0], ":🟨")

    if guess[1] in random_words[1]:
      print(guess[1], ":🟩")
    elif guess[1] not in random_words:
      print(guess[1], ":⬜")
    elif guess[1] in random_words[0] or guess[1] in random_words[2] or guess[1] in random_words[3] or guess[1] in random_words[4]:
      print(guess[1], ":🟨")

    if guess[2] in random_words[2]:
      print(guess[2], ":🟩")
    elif guess[2] not in random_words:
      print(guess[2], ":⬜")
    elif guess[2] in random_words[0] or guess[2] in random_words[1] or guess[2] in random_words[3] or guess[2] in random_words[4]:
      print(guess[2], ":🟨")

    if guess[3] in random_words[3]:
      print(guess[3], ":🟩")
    elif guess[3] not in random_words:
      print(guess[3], ":⬜")
    elif guess[3] in random_words[0] or guess[3] in random_words[1] or guess[3] in random_words[2] or guess[3] in random_words[4]:
      print(guess[3], ":🟨")

    if guess[4] in random_words[4]:
      print(guess[4], ":🟩")
    elif guess[4] not in random_words:
      print(guess[4], ":⬜")
    elif guess[4] in random_words[0] or guess[4] in random_words[1] or guess[4] in random_words[2] or guess[4] in random_words[3]:
      print(guess[4], ":🟨")

  if guess[0] in random_words[0] and guess[1] in random_words[1] and guess[2] in random_words[2] and guess[3] in random_words[3] and guess[4] in random_words[4]:
    print("Ganaste!") #"You won!"