# -*- coding: utf-8 -*-
"""pociones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVNmf2uc72d0RwqV6RAj8vIQSrzz8x7
"""

import random

words = ["trees", "apple", "paper", "hotel", "names"] #Add your own list of words here!
word = random.choice(words)
print(word)

for attempt in range(5):
  user_ans = input("Guess the word: ")
  if len(user_ans) != 5:
    print("Your word must be 5 characters long.")
  else:
    for position, letter in enumerate(user_ans):
      if letter == word[position]:
        print(letter, "🟩")
      elif letter in word:
        print(letter, "🟨")
      else:
        print(letter, "⬜")

